site_name: Node.js
site_url: https://nodejsdev.ru/
site_description: Справочник Node.js с примерами кода
site_author: nodejsdev.ru
copyright: (☭) Народное достояние с 2021 года

repo_name: 'Справочник на Github'
repo_url: 'https://github.com/xsltdev/nodejsdev.ru'

theme:
    name: material
    custom_dir: overrides
    palette:
        - media: '(prefers-color-scheme)'
          primary: green
          accent: green
          toggle:
              icon: material/brightness-auto
              name: Переключиться на светлую тему
        - media: '(prefers-color-scheme: light)'
          scheme: default
          primary: green
          accent: green
          toggle:
              icon: material/toggle-switch-off-outline
              name: Переключиться на тёмную тему
        - media: '(prefers-color-scheme: dark)'
          scheme: slate
          primary: green
          accent: green
          toggle:
              icon: material/toggle-switch
              name: Переключиться на системную тему
    language: ru
    features:
        - navigation.prune
        - navigation.tabs
        - navigation.tracking
        - navigation.top
        - navigation.footer
        - navigation.indexes
        - content.action.edit
        - content.tabs.link
        - content.code.copy
    favicon: nodejs.svg
    logo: nodejs-white.svg

extra:
    generator: false
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/xsltdev
          name: GitHub
        - icon: fontawesome/regular/heart
          link: https://boosty.to/bndby
          name: Boosty
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/bndby/
          name: LinkedIn

markdown_extensions:
    - admonition
    - toc:
          permalink: true
    - pymdownx.extra
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.highlight:
          pygments_lang_class: true
          linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.smartsymbols

plugins:
    - search:
          lang:
              - ru
              - en
    - awesome-pages
    - social
    - minify:
          minify_html: true
          htmlmin_opts:
              remove_comments: true
          cache_safe: true
    - glightbox:
          auto_caption: true
          skip_classes:
              - nolightbox

extra_css:
    - '/assets/stylesheets/styles.css?7'
